import React, { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { format } from "date-fns";
import { 
  FileText, 
  Plus, 
  Eye, 
  Edit, 
  Trash2, 
  Upload,
  Download,
  Calendar,
  Send
} from "lucide-react";

interface RfpAddendum {
  id: string;
  rfp_id: string;
  addendum_number: number;
  title: string;
  description?: string;
  content?: string;
  attachments: any;
  published_at?: string;
  created_by: string;
  created_at: string;
  updated_at: string;
  is_published: boolean;
}

interface RfpAddendumsProps {
  rfpId: string;
  canManage?: boolean;
}

export const RfpAddendums: React.FC<RfpAddendumsProps> = ({ 
  rfpId, 
  canManage = false 
}) => {
  const { toast } = useToast();
  const [addendums, setAddendums] = useState<RfpAddendum[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingAddendum, setEditingAddendum] = useState<RfpAddendum | null>(null);
  const [selectedAddendum, setSelectedAddendum] = useState<RfpAddendum | null>(null);
  const [isViewDialogOpen, setIsViewDialogOpen] = useState(false);

  // Form state
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    content: '',
    attachments: [] as any[]
  });

  useEffect(() => {
    fetchAddendums();
  }, [rfpId]);

  useEffect(() => {
    if (editingAddendum) {
      setFormData({
        title: editingAddendum.title,
        description: editingAddendum.description || '',
        content: editingAddendum.content || '',
        attachments: editingAddendum.attachments || []
      });
    } else {
      setFormData({
        title: '',
        description: '',
        content: '',
        attachments: []
      });
    }
  }, [editingAddendum]);

  const fetchAddendums = async () => {
    try {
      let query = supabase
        .from('rfp_addendums')
        .select('*')
        .eq('rfp_id', rfpId)
        .order('addendum_number', { ascending: true });

      // If user can't manage, only show published addendums
      if (!canManage) {
        query = query.eq('is_published', true);
      }

      const { data, error } = await query;

      if (error) throw error;
      setAddendums(data || []);
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message || "Failed to fetch addendums",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('User not authenticated');

      if (editingAddendum) {
        // Update existing addendum
        const { error } = await supabase
          .from('rfp_addendums')
          .update({
            title: formData.title,
            description: formData.description,
            content: formData.content,
            attachments: formData.attachments
          })
          .eq('id', editingAddendum.id);

        if (error) throw error;

        toast({
          title: "Success",
          description: "Addendum updated successfully",
        });
      } else {
        // Create new addendum - the addendum_number will be auto-generated by the trigger
        const { error } = await supabase
          .from('rfp_addendums')
          .insert({
            rfp_id: rfpId,
            title: formData.title,
            description: formData.description || null,
            content: formData.content || null,
            attachments: formData.attachments,
            created_by: user.id
          } as any);

        if (error) throw error;

        toast({
          title: "Success",
          description: "Addendum created successfully",
        });
      }

      setFormData({
        title: '',
        description: '',
        content: '',
        attachments: []
      });
      setEditingAddendum(null);
      setIsDialogOpen(false);
      fetchAddendums();
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message || "Failed to save addendum",
        variant: "destructive",
      });
    }
  };

  const handlePublish = async (addendumId: string) => {
    try {
      const { error } = await supabase
        .from('rfp_addendums')
        .update({
          is_published: true,
          published_at: new Date().toISOString()
        })
        .eq('id', addendumId);

      if (error) throw error;

      toast({
        title: "Success",
        description: "Addendum published successfully",
      });

      fetchAddendums();
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message || "Failed to publish addendum",
        variant: "destructive",
      });
    }
  };

  const handleDelete = async (addendumId: string) => {
    try {
      const { error } = await supabase
        .from('rfp_addendums')
        .delete()
        .eq('id', addendumId);

      if (error) throw error;

      toast({
        title: "Success",
        description: "Addendum deleted successfully",
      });

      fetchAddendums();
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message || "Failed to delete addendum",
        variant: "destructive",
      });
    }
  };

  const openEditDialog = (addendum: RfpAddendum) => {
    setEditingAddendum(addendum);
    setIsDialogOpen(true);
  };

  const openCreateDialog = () => {
    setEditingAddendum(null);
    setIsDialogOpen(true);
  };

  const viewAddendum = (addendum: RfpAddendum) => {
    setSelectedAddendum(addendum);
    setIsViewDialogOpen(true);
  };

  if (isLoading) {
    return <div className="p-6">Loading addendums...</div>;
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h3 className="text-lg font-semibold">RFP Addendums</h3>
        
        {canManage && (
          <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
            <DialogTrigger asChild>
              <Button onClick={openCreateDialog}>
                <Plus className="h-4 w-4 mr-2" />
                Create Addendum
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-2xl">
              <DialogHeader>
                <DialogTitle>
                  {editingAddendum ? 'Edit Addendum' : 'Create New Addendum'}
                </DialogTitle>
              </DialogHeader>
              <form onSubmit={handleSubmit} className="space-y-4">
                <div>
                  <Label htmlFor="title">Title</Label>
                  <Input
                    id="title"
                    value={formData.title}
                    onChange={(e) => setFormData(prev => ({ ...prev, title: e.target.value }))}
                    placeholder="Enter addendum title"
                    required
                  />
                </div>

                <div>
                  <Label htmlFor="description">Description</Label>
                  <Textarea
                    id="description"
                    value={formData.description}
                    onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
                    placeholder="Brief description of the addendum"
                    rows={2}
                  />
                </div>

                <div>
                  <Label htmlFor="content">Content</Label>
                  <Textarea
                    id="content"
                    value={formData.content}
                    onChange={(e) => setFormData(prev => ({ ...prev, content: e.target.value }))}
                    placeholder="Detailed content of the addendum"
                    rows={8}
                  />
                </div>

                <div className="flex justify-end space-x-2">
                  <Button type="button" variant="outline" onClick={() => setIsDialogOpen(false)}>
                    Cancel
                  </Button>
                  <Button type="submit">
                    {editingAddendum ? 'Update' : 'Create'} Addendum
                  </Button>
                </div>
              </form>
            </DialogContent>
          </Dialog>
        )}
      </div>

      <div className="grid gap-4">
        {addendums.map((addendum) => (
          <Card key={addendum.id}>
            <CardHeader>
              <div className="flex items-start justify-between">
                <div className="space-y-1">
                  <div className="flex items-center space-x-2">
                    <Badge variant="outline">
                      Addendum #{addendum.addendum_number}
                    </Badge>
                    <h4 className="font-semibold">{addendum.title}</h4>
                    {addendum.is_published ? (
                      <Badge variant="default">Published</Badge>
                    ) : (
                      <Badge variant="secondary">Draft</Badge>
                    )}
                  </div>
                  {addendum.description && (
                    <p className="text-sm text-muted-foreground">{addendum.description}</p>
                  )}
                  <div className="flex items-center space-x-4 text-xs text-muted-foreground">
                    <span className="flex items-center">
                      <Calendar className="h-3 w-3 mr-1" />
                      Created: {format(new Date(addendum.created_at), "PPp")}
                    </span>
                    {addendum.published_at && (
                      <span className="flex items-center">
                        <Send className="h-3 w-3 mr-1" />
                        Published: {format(new Date(addendum.published_at), "PPp")}
                      </span>
                    )}
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => viewAddendum(addendum)}
                  >
                    <Eye className="h-4 w-4 mr-2" />
                    View
                  </Button>
                  {canManage && (
                    <>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => openEditDialog(addendum)}
                      >
                        <Edit className="h-4 w-4 mr-2" />
                        Edit
                      </Button>
                      {!addendum.is_published && (
                        <Button
                          variant="default"
                          size="sm"
                          onClick={() => handlePublish(addendum.id)}
                        >
                          <Send className="h-4 w-4 mr-2" />
                          Publish
                        </Button>
                      )}
                      <AlertDialog>
                        <AlertDialogTrigger asChild>
                          <Button variant="outline" size="sm">
                            <Trash2 className="h-4 w-4 mr-2" />
                            Delete
                          </Button>
                        </AlertDialogTrigger>
                        <AlertDialogContent>
                          <AlertDialogHeader>
                            <AlertDialogTitle>Delete Addendum</AlertDialogTitle>
                            <AlertDialogDescription>
                              Are you sure you want to delete this addendum? This action cannot be undone.
                            </AlertDialogDescription>
                          </AlertDialogHeader>
                          <AlertDialogFooter>
                            <AlertDialogCancel>Cancel</AlertDialogCancel>
                            <AlertDialogAction onClick={() => handleDelete(addendum.id)}>
                              Delete
                            </AlertDialogAction>
                          </AlertDialogFooter>
                        </AlertDialogContent>
                      </AlertDialog>
                    </>
                  )}
                </div>
              </div>
            </CardHeader>
          </Card>
        ))}
      </div>

      {/* View Addendum Dialog */}
      {selectedAddendum && (
        <Dialog open={isViewDialogOpen} onOpenChange={setIsViewDialogOpen}>
          <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle className="flex items-center space-x-2">
                <Badge variant="outline">
                  Addendum #{selectedAddendum.addendum_number}
                </Badge>
                <span>{selectedAddendum.title}</span>
              </DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              {selectedAddendum.description && (
                <div>
                  <h4 className="font-medium mb-2">Description</h4>
                  <p className="text-sm text-muted-foreground">{selectedAddendum.description}</p>
                </div>
              )}
              
              {selectedAddendum.content && (
                <div>
                  <h4 className="font-medium mb-2">Content</h4>
                  <div className="prose prose-sm max-w-none">
                    <pre className="whitespace-pre-wrap text-sm">{selectedAddendum.content}</pre>
                  </div>
                </div>
              )}

              <div className="flex items-center space-x-4 text-sm text-muted-foreground pt-4 border-t">
                <span>Created: {format(new Date(selectedAddendum.created_at), "PPP p")}</span>
                {selectedAddendum.published_at && (
                  <span>Published: {format(new Date(selectedAddendum.published_at), "PPP p")}</span>
                )}
                <Badge variant={selectedAddendum.is_published ? "default" : "secondary"}>
                  {selectedAddendum.is_published ? "Published" : "Draft"}
                </Badge>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      )}

      {addendums.length === 0 && (
        <Card>
          <CardContent className="p-8 text-center">
            <FileText className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
            <p className="text-muted-foreground">No addendums available.</p>
            {canManage && (
              <p className="text-sm text-muted-foreground mt-2">
                Create the first addendum to provide updates and clarifications to vendors.
              </p>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
};