
import React, { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/components/ui/use-toast';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { Loader2, RefreshCw, Mail } from 'lucide-react';

interface ResetPasswordDialogProps {
  userId: string;
  userEmail: string;
  isOpen: boolean;
  onClose: () => void;
}

const ResetPasswordDialog = ({ userId, userEmail, isOpen, onClose }: ResetPasswordDialogProps) => {
  const { toast } = useToast();
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [autoGenerate, setAutoGenerate] = useState(false);
  const [sendEmail, setSendEmail] = useState(false);
  
  const generatePassword = () => {
    const length = 12;
    const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*";
    let password = "";
    
    // Ensure at least one character from each required type
    password += "ABCDEFGHIJKLMNOPQRSTUVWXYZ"[Math.floor(Math.random() * 26)]; // uppercase
    password += "abcdefghijklmnopqrstuvwxyz"[Math.floor(Math.random() * 26)]; // lowercase
    password += "0123456789"[Math.floor(Math.random() * 10)]; // number
    password += "!@#$%^&*"[Math.floor(Math.random() * 8)]; // special char
    
    // Fill the rest randomly
    for (let i = password.length; i < length; i++) {
      password += charset[Math.floor(Math.random() * charset.length)];
    }
    
    // Shuffle the password
    return password.split('').sort(() => 0.5 - Math.random()).join('');
  };
  
  const handleGeneratePassword = () => {
    const generated = generatePassword();
    setNewPassword(generated);
    setConfirmPassword(generated);
  };
  
  const handleResetPassword = async () => {
    // Auto-generate password if requested
    if (autoGenerate && !newPassword) {
      handleGeneratePassword();
      // Wait a moment for state to update
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    
    const passwordToUse = autoGenerate ? generatePassword() : newPassword;
    
    // Validation
    if (!passwordToUse) {
      toast({
        title: "Error",
        description: "Password cannot be empty",
        variant: "destructive",
      });
      return;
    }
    
    if (passwordToUse.length < 6) {
      toast({
        title: "Error",
        description: "Password must be at least 6 characters long",
        variant: "destructive",
      });
      return;
    }
    
    if (!autoGenerate && passwordToUse !== confirmPassword) {
      toast({
        title: "Error",
        description: "Passwords do not match",
        variant: "destructive",
      });
      return;
    }
    
    try {
      setIsSubmitting(true);
      
      console.log('Resetting password for user:', userEmail);
      
      // Call the Edge Function to reset password
      const { data, error } = await supabase.functions.invoke('reset-user-password', {
        body: {
          userId: userId,
          newPassword: passwordToUse,
          userEmail: userEmail,
          sendEmail: sendEmail,
          autoGenerated: autoGenerate
        }
      });
      
      if (error) {
        console.error('Edge function error:', error);
        throw new Error(error.message || 'Failed to call reset password function');
      }
      
      if (data.error) {
        throw new Error(data.error);
      }
      
      let successMessage = data.message || `Password reset for ${userEmail}`;
      if (sendEmail) {
        successMessage += " Password sent via email.";
      } else if (autoGenerate) {
        successMessage += ` New password: ${passwordToUse}`;
      }
      
      toast({
        title: "Success",
        description: successMessage,
      });
      
      setNewPassword('');
      setConfirmPassword('');
      setAutoGenerate(false);
      setSendEmail(false);
      onClose();
      
    } catch (error: any) {
      console.error('Error resetting password:', error);
      toast({
        title: "Failed to reset password",
        description: error.message || "An unexpected error occurred",
        variant: "destructive",
      });
    } finally {
      setIsSubmitting(false);
    }
  };
  
  return (
    <AlertDialog open={isOpen} onOpenChange={onClose}>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>Reset Password</AlertDialogTitle>
          <AlertDialogDescription>
            Set a new password for user: <strong>{userEmail}</strong>
          </AlertDialogDescription>
        </AlertDialogHeader>
        
        <div className="space-y-4 py-4">
          <div className="flex items-center space-x-2">
            <Checkbox 
              id="auto-generate" 
              checked={autoGenerate}
              onCheckedChange={(checked) => setAutoGenerate(checked === true)}
            />
            <Label htmlFor="auto-generate" className="text-sm font-medium">
              Auto-generate secure password
            </Label>
          </div>
          
          {!autoGenerate && (
            <>
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <label htmlFor="new-password" className="text-sm font-medium">New Password</label>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={handleGeneratePassword}
                  >
                    <RefreshCw className="w-3 h-3 mr-1" />
                    Generate
                  </Button>
                </div>
                <Input
                  id="new-password"
                  type="password"
                  placeholder="Enter new password"
                  value={newPassword}
                  onChange={(e) => setNewPassword(e.target.value)}
                  disabled={autoGenerate}
                />
              </div>
              
              <div className="space-y-2">
                <label htmlFor="confirm-password" className="text-sm font-medium">Confirm Password</label>
                <Input
                  id="confirm-password"
                  type="password"
                  placeholder="Confirm new password"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  disabled={autoGenerate}
                />
              </div>
            </>
          )}
          
          <div className="flex items-center space-x-2">
            <Checkbox 
              id="send-email" 
              checked={sendEmail}
              onCheckedChange={(checked) => setSendEmail(checked === true)}
            />
            <Label htmlFor="send-email" className="text-sm font-medium flex items-center">
              <Mail className="w-4 h-4 mr-1" />
              Send new password via email
            </Label>
          </div>
        </div>
        
        <AlertDialogFooter>
          <AlertDialogCancel disabled={isSubmitting}>Cancel</AlertDialogCancel>
          <AlertDialogAction 
            onClick={handleResetPassword}
            disabled={isSubmitting}
            className="bg-blue-600 hover:bg-blue-700"
          >
            {isSubmitting ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Resetting...
              </>
            ) : (
              "Reset Password"
            )}
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
};

export default ResetPasswordDialog;
