
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface ResetPasswordRequest {
  userId: string;
  newPassword: string;
  userEmail: string;
  sendEmail?: boolean;
  autoGenerated?: boolean;
}

const handler = async (req: Request): Promise<Response> => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Create Supabase client with service role key for admin operations
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      {
        auth: {
          autoRefreshToken: false,
          persistSession: false
        }
      }
    );

    // Get the request body
    const { userId, newPassword, userEmail, sendEmail = false, autoGenerated = false }: ResetPasswordRequest = await req.json();

    console.log(`[ResetPassword] Attempting to reset password for user: ${userEmail} (${userId})`);

    // Validate inputs
    if (!userId || !newPassword) {
      return new Response(
        JSON.stringify({ error: 'Missing required fields: userId and newPassword' }),
        { 
          status: 400, 
          headers: { 'Content-Type': 'application/json', ...corsHeaders } 
        }
      );
    }

    if (newPassword.length < 6) {
      return new Response(
        JSON.stringify({ error: 'Password must be at least 6 characters long' }),
        { 
          status: 400, 
          headers: { 'Content-Type': 'application/json', ...corsHeaders } 
        }
      );
    }

    // Use admin client to update user password
    const { data, error } = await supabaseAdmin.auth.admin.updateUserById(userId, {
      password: newPassword
    });

    if (error) {
      console.error('[ResetPassword] Error updating password:', error);
      return new Response(
        JSON.stringify({ error: error.message }),
        { 
          status: 400, 
          headers: { 'Content-Type': 'application/json', ...corsHeaders } 
        }
      );
    }

    console.log(`[ResetPassword] Successfully reset password for user: ${userEmail}`);

    // Send email with new password if requested
    if (sendEmail) {
      try {
        const emailSubject = 'Your Password Has Been Reset';
        const emailContent = `
          <h2>Password Reset Notification</h2>
          <p>Hello,</p>
          <p>Your password has been reset by an administrator.</p>
          ${autoGenerated ? `<p><strong>Your new password is:</strong> ${newPassword}</p>` : '<p>Please use the new password provided to you by the administrator.</p>'}
          <p>For security reasons, we recommend changing this password after your next login.</p>
          <p>If you did not request this password reset, please contact your administrator immediately.</p>
          <br>
          <p>Best regards,<br>System Administrator</p>
        `;
        
        const { error: emailError } = await supabaseAdmin.functions.invoke('send-email', {
          body: {
            to: userEmail,
            subject: emailSubject,
            html: emailContent
          }
        });

        if (emailError) {
          console.error('[ResetPassword] Error sending email:', emailError);
          // Don't fail the password reset if email fails
        } else {
          console.log(`[ResetPassword] Email sent to: ${userEmail}`);
        }
      } catch (emailError) {
        console.error('[ResetPassword] Email sending failed:', emailError);
        // Don't fail the password reset if email fails
      }
    }

    // Log the activity
    const { error: logError } = await supabaseAdmin
      .from('activity_logs')
      .insert({
        user_id: userId,
        action: 'password_reset_by_admin',
        details: { 
          target_user: userEmail,
          reset_by: 'admin_function',
          auto_generated: autoGenerated,
          email_sent: sendEmail
        }
      });

    if (logError) {
      console.error('[ResetPassword] Error logging activity:', logError);
    }

    return new Response(
      JSON.stringify({ 
        success: true, 
        message: `Password reset successfully for ${userEmail}` 
      }),
      { 
        status: 200, 
        headers: { 'Content-Type': 'application/json', ...corsHeaders } 
      }
    );

  } catch (error: any) {
    console.error('[ResetPassword] Unexpected error:', error);
    return new Response(
      JSON.stringify({ error: error.message || 'An unexpected error occurred' }),
      { 
        status: 500, 
        headers: { 'Content-Type': 'application/json', ...corsHeaders } 
      }
    );
  }
};

serve(handler);
